name: Prettier Autofix

on:
  push:
    branches: ["**"]

permissions:
  contents: write

jobs:
  prettier:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Prettier
        run: npx prettier --write "kubejs/**/*.{js,json}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format with Prettier"